### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by dabrahams** [ohler/ert#1]
I'm just
trying to get it installed and am already confused.  It's hosted in
Git but it tries to install itself into an active bzr repo?  Even
after I hack up the install.sh to avoid bzr, installation doesn't work.
What am I missing?

https://gist.github.com/729587

More to the point:
- how do I install this thing in my emacs?
- how do I distribute regression tests with my elisp package?

Thanks!

**Comment by ohler** [comment]
Ha, thanks for reporting this. It didn't occur to me that this could be confusing. Ignore the install script; it is only used to produce a patch to submit to Emacs for inclusion.

I added a README file. If this is still unclear, please let me know.
